# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Payment Accuracy
description: >- # this means to ignore newlines until "baseurl:"
  Explore the payment accuracy of the U.S. Government.
url: "" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: ""

# This custom var is used only in meta tags in _head.html. It does not break sites for staging, dev, etc.
domain: "https://paymentaccuracy.gov"

timezone: "America/New_York"

# Build settings
markdown: kramdown

# NOTE: The markdown files in these folders are auto-generated. See README.md for how to generate the markdown files.

# Plugins
plugins:
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - ".ruby-version"
  - ".sass-cache"
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - css
  - image-templates
  - CODE_OF_CONDUCT.md
  - Staticfile
  - .github
  - documentation
